import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../auth";
import Navbar from "../components/Navbar";
import { ProductProvider } from "../context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const session = await auth();
	return (
		<SessionProvider session={session}>
			<ProductProvider>
				<html lang="en">
					<body className={inter.className}>
						<div className="mx-auto max-w-screen-lg h-screen flex flex-col">
							<Navbar />
							<div className="flex-grow">{children}</div>
						</div>
					</body>
				</html>
			</ProductProvider>
		</SessionProvider>
	);
}
